# Generated by Django 6.1.1 on 2026-09-17 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['step_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(choices=[('face', 'Face Analysis'), ('outfit', 'Outfit Analysis'), ('combined', 'Combined Analysis')], default='face', max_length=20)),
                ('look_name', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('confidence_overall', models.FloatField(default=0.0)),
                ('confidence_data', models.JSONField(blank=True, default=dict)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('face', 'Face Photo'), ('outfit', 'Outfit Photo')], max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='analysis/%Y/%m/')),
                ('image_data_uri', models.TextField(blank=True, help_text='Base64 preview data for ephemeral storage')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_quality', models.JSONField(blank=True, default=dict)),
                ('face_visibility', models.JSONField(blank=True, default=dict)),
                ('complexion_observations', models.JSONField(blank=True, default=dict)),
                ('visible_undertone_indicators', models.JSONField(blank=True, default=dict)),
                ('face_shape_estimate', models.JSONField(blank=True, default=dict)),
                ('eye_area', models.JSONField(blank=True, default=dict)),
                ('lip_area', models.JSONField(blank=True, default=dict)),
                ('brow_area', models.JSONField(blank=True, default=dict)),
                ('existing_makeup', models.JSONField(blank=True, default=dict)),
                ('color_harmony', models.JSONField(blank=True, default=dict)),
                ('recommended_makeup_direction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_analysis', to='core.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('product_direction', models.CharField(max_length=150)),
                ('color_name', models.CharField(blank=True, max_length=80)),
                ('hex_color', models.CharField(default='#C48D7F', max_length=7)),
                ('temperature', models.CharField(blank=True, max_length=40)),
                ('saturation', models.CharField(blank=True, max_length=40)),
                ('brightness', models.CharField(blank=True, max_length=40)),
                ('finish', models.CharField(blank=True, max_length=60)),
                ('intensity', models.CharField(blank=True, max_length=60)),
                ('placement', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('extra_details', models.JSONField(blank=True, default=dict)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.analysissession')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='OutfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('secondary_colors', models.JSONField(blank=True, default=list)),
                ('pattern', models.CharField(blank=True, max_length=80)),
                ('contrast', models.CharField(blank=True, max_length=60)),
                ('temperature', models.CharField(blank=True, max_length=60)),
                ('saturation', models.CharField(blank=True, max_length=60)),
                ('brightness', models.CharField(blank=True, max_length=60)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('formality', models.CharField(blank=True, max_length=60)),
                ('overall_aesthetic', models.CharField(blank=True, max_length=120)),
                ('raw_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_analysis', to='core.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, help_text='e.g. Liquid Blush, Powder Foundation', max_length=100)),
                ('finish', models.CharField(blank=True, help_text='e.g. Matte, Dewy, Satin, Radiant, Shimmer', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback web image URL')),
                ('product_url', models.URLField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productcategory')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductShade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shade_code', models.CharField(blank=True, max_length=60)),
                ('hex_color', models.CharField(default='#C48D7F', help_text='HEX color approximation', max_length=7)),
                ('undertone', models.CharField(blank=True, help_text='warm, cool, neutral, olive', max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='core.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(default=0.9)),
                ('role', models.CharField(blank=True, help_text='e.g. Primary Base, Accent Lip', max_length=100)),
                ('usage', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_products', to='core.makeuprecommendation')),
                ('shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productshade')),
            ],
            options={
                'ordering': ['-compatibility_score'],
            },
        ),
        migrations.CreateModel(
            name='SavedLook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=140)),
                ('look_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(default='face', max_length=20)),
                ('routine_data', models.JSONField(default=list, help_text='Ordered steps for the routine')),
                ('visual_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_looks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedLookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=60)),
                ('usage_notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('saved_look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.savedlook')),
                ('shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productshade')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('custom_shade_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_in_makeup_bag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='core.product')),
                ('shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productshade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('skin_type_preference', models.CharField(blank=True, help_text='e.g. dry, oily, combination, normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_784c92_idx'),
        ),
    ]
